package lame.laven.msgs;

public enum SubmissionMsg {
   SERVER_URI,
   retrieving_settings,
   lookup_perforce,
   unknown_config_class,
   config_class,
   no_server,
   no_settings,
   incomplete_config,
   incomplete_config_ex,
   not_connected,
   not_connected_ex,
   p4_connecting,
   p4_connecting_ex,
   p4_connected,
   unopened_pom,
   unopened_pom_ex,
   pom_cl_unknown,
   using_pom,
   building_ver,
   build_version_ex,
   pom_update_failure,
   pom_update_version,
   pom_old_version, 
   pom_new_version, 
   submiting,
   not_submitted,
   removing_backup,
   recording,
   recording_prefix,
   recording_status, 
   reverting_pom,
   reverting_pom_ex, 
   ;
}
